import type { TourStep } from "./GuidedTour.tsx";
import type { ConfigSectionId } from "../views/ConfigView/configRouting.ts";

export { CONFIG_SECTIONS } from "../views/ConfigView/configRouting.ts";

/** First-run tour: introduces the three top-level tabs. */
export const MAIN_NAV_TOUR: TourStep[] = [
  {
    target: '[data-tour="nav-overview"]',
    title: "Overview",
    body: "Your dashboard: task activity, throughput, AI cost, and system health at a glance.",
    placement: "bottom",
  },
  {
    target: '[data-tour="nav-tasks"]',
    title: "Tasks",
    body: "Every ticket and review VE is working on, with live progress and agent logs.",
    placement: "bottom",
  },
  {
    target: '[data-tour="nav-config"]',
    title: "Configuration",
    body: "Set up integrations, agents, and projects here.",
    placement: "bottom",
    optional: true,
  },
];

/** Second tour: follows the setup workflow from providers to the first project. */
export const CONFIG_WORKFLOW_TOUR: TourStep[] = [
  {
    target: '[data-tour="config-nav-integrations"]',
    title: "Integrations first",
    body: "Connect the ticket, source-control, review, and agent providers VE will use.",
    placement: "right",
    completion: "route-changes",
    optional: true,
  },
  {
    target: '[data-tour="config-nav-agents"]',
    title: "Agents library",
    body: "Create a reusable coding or review agent with its model, prompts, and execution settings.",
    placement: "right",
    completion: "route-changes",
    optional: true,
  },
  {
    target: '[data-tour="config-nav-projects"]',
    title: "Projects",
    body: "Once your integrations and agent are ready, create a project that connects them to a real workflow.",
    placement: "right",
    completion: "route-changes",
    optional: true,
  },
  {
    target: '[data-tour="tutorial-launcher"]',
    title: "Need a refresher?",
    body: "Use the ? anytime to replay this tour when you need it.",
    placement: "left",
  },
];

export const CONFIG_SECTION_TOURS: Record<ConfigSectionId, TourStep[]> = {
  overview: CONFIG_WORKFLOW_TOUR,
  integrations: [
    {
      target: '[data-tour="integrations-add"]',
      title: "Add an integration",
      body: "Create a provider connection, then test and save its credentials.",
      placement: "bottom",
      completion: "route-changes",
      optional: true,
    },
    {
      target: '[data-tour="integration-provider-picker"]',
      title: "Choose the provider",
      body: "Select the provider that owns the ticket, repository, review, or agent connection you are configuring.",
      placement: "bottom",
      advance: "click",
      optional: true,
    },
    {
      target: '[data-tour="integration-form-name"]',
      title: "Name the connection",
      body: "Use a recognizable name so this integration is easy to identify when you assign it to a project or agent.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="integration-form-provider-fields"]',
      title: "Configure provider access",
      body: "These fields contain the provider-specific host and authentication settings. Secret values stay protected by the admin server.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="integration-form-ssh"]',
      title: "SSH authentication",
      body: "When this provider supports SSH, use this section for the key and host settings needed for repository access.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="integration-form-advanced-toggle"]',
      title: "Advanced settings",
      body: "Open this section only when the provider exposes optional connection settings beyond the required fields.",
      placement: "right",
      advance: "click",
      optional: true,
    },
    {
      target: '[data-tour="integration-form-advanced-fields"]',
      title: "Optional provider values",
      body: "Review advanced values such as endpoints or additional provider options before testing the connection.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="integration-form-oauth"]',
      title: "OAuth assistance",
      body: "Some providers offer a device or redirect flow here to obtain a token without entering it into the form manually.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="integration-form-actions"]',
      title: "Test and save",
      body: "Run Test to verify the connection, then use Add integration or Save changes when the form is complete.",
      placement: "top",
      advance: "continue",
      optional: true,
    },
  ],
  oauth: [
    {
      target: '[data-tour="oauth-register"]',
      title: "Register an app",
      body: "Add a client ID for the provider host that will authorize VE.",
      placement: "bottom",
      completion: "route-changes",
      optional: true,
    },
    {
      target: '[data-tour="oauth-form-provider"]',
      title: "Choose the provider",
      body: "Select the provider whose OAuth application will issue the authorization token.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="oauth-form-base-url"]',
      title: "Set the provider host",
      body: "Enter the base URL of the provider instance that will handle the OAuth flow.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="oauth-form-client-id"]',
      title: "Add the client ID",
      body: "Paste the OAuth application client ID registered with that provider host.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="oauth-form-actions"]',
      title: "Register the app",
      body: "Review the provider, host, and client ID, then use Register app to store the application registration.",
      placement: "top",
      advance: "continue",
    },
  ],
  agents: [
    {
      target: '[data-tour="agents-new"]',
      title: "Create an agent",
      body: "Choose its provider, model, prompts, and execution settings.",
      placement: "bottom",
      completion: "route-changes",
      optional: true,
    },
    {
      target: '[data-tour="agent-form-basics"]',
      title: "Define the agent",
      body: "Set the agent name and choose whether it generates code or performs reviews. Review strategies appear when the selected provider supports them.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="agent-form-integration"]',
      title: "Choose the agent integration",
      body: "Select an enabled agent-execution integration. Its provider determines the available models and provider settings.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="agent-form-model"]',
      title: "Choose a model",
      body: "Select a discovered model or leave the field on the provider default when the agent should follow the provider's default choice.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="agent-form-concurrency"]',
      title: "Set concurrency",
      body: "Max Concurrent limits how many cycles this agent can run at the same time.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="agent-form-prompts"]',
      title: "Assign the prompts",
      body: "Choose the permanent System Prompt and workflow Instructions Prompt. Coding agents can also use a separate prompt for retry feedback.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="agent-form-provider-settings-toggle"]',
      title: "Provider settings",
      body: "Open this section to review provider-specific execution options when the selected integration exposes them.",
      placement: "right",
      advance: "click",
      optional: true,
    },
    {
      target: '[data-tour="agent-form-provider-settings"]',
      title: "Execution options",
      body: "These settings refine the selected provider without changing the shared agent workflow.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="agent-form-tool-authorization"]',
      title: "Tool authorization",
      body: "Review the provider's tool permissions here. The sandbox safety floor remains enforced independently.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="agent-form-actions"]',
      title: "Save the agent",
      body: "When the integration, prompts, and execution settings are ready, use Create agent or Save changes.",
      placement: "top",
      advance: "continue",
    },
  ],
  projects: [
    {
      target: '[data-tour="projects-new-button"]',
      title: "Create a project",
      body: "Define an execution unit that turns your configured providers into a workflow.",
      placement: "bottom",
      completion: "route-changes",
      optional: true,
    },
    {
      target: '[data-tour="project-form-name"]',
      title: "Name the project",
      body: "Choose a name that describes the workflow this project will run.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="project-form-type"]',
      title: "Choose the project type",
      body: "Coding projects start from tickets and push changes. Review projects watch repository changes and post review feedback.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="project-form-agent"]',
      title: "Assign the agent",
      body: "Select the enabled coding or review agent that will execute this project's workflow.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="project-ticket-source"]',
      title: "Connect the ticket source",
      body: "Coding projects use this integration and project key to find work that should become agent cycles.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="project-ticket-key"]',
      title: "Select the ticket project",
      body: "Choose a discovered ticket project or enter its key when discovery is unavailable.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="project-push-targets"]',
      title: "Configure push targets",
      body: "Each push target identifies the source-control integration, repository, clone URL, and branch where generated changes will be prepared.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="project-repository-key"]',
      title: "Choose the repository",
      body: "Select a discovered repository to fill its clone URL and default branch, or enter the repository key manually.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="project-target-branch"]',
      title: "Choose the target branch",
      body: "Set the branch that will receive the generated changes or review checkout.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="project-workspace-scan"]',
      title: "Scan the workspace",
      body: "For a workspace repository, scan manifests to discover related components before deciding which repositories VE should edit or push.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="project-review-config"]',
      title: "Configure review repositories",
      body: "Review projects use the review integration and one or more repository keys to identify the changes VE should inspect.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="project-options"]',
      title: "Tune workflow options",
      body: "Coding projects can customize the Gerrit topic and ticket or CI feedback behavior without changing the core provider connections.",
      placement: "right",
      advance: "continue",
      optional: true,
    },
    {
      target: '[data-tour="project-skill-sources"]',
      title: "Add external skills",
      body: "Optional skill sources are staged host-side into the provider's native skill directory before the agent runs.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="project-post-clone"]',
      title: "Prepare after cloning",
      body: "Use the post-clone script for setup commands that must run after checkout and before the agent starts.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="project-form-actions"]',
      title: "Save the project",
      body: "Review the selected providers and workflow options, then use Create Project or Save Project when the configuration is complete.",
      placement: "top",
      advance: "continue",
    },
  ],
  prompts: [
    {
      target: '[data-tour="prompts-new"]',
      title: "Create a prompt",
      body: "Add reusable instructions for coding, review, or a custom workflow.",
      placement: "bottom",
      completion: "route-changes",
      optional: true,
    },
    {
      target: '[data-tour="prompt-form-label"]',
      title: "Name the prompt",
      body: "Use a concise label that will be recognizable when an agent assigns its prompts.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="prompt-form-type"]',
      title: "Choose the prompt role",
      body: "System prompts define durable behavior; Instructions prompts define the workflow guidance added to a task.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="prompt-form-content"]',
      title: "Write the content",
      body: "Enter the complete prompt body. Keep durable safety and commit boundaries in System prompts and task guidance in Instructions prompts.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="prompt-form-actions"]',
      title: "Save the prompt",
      body: "Review the label, role, and content, then use Create prompt or Save changes.",
      placement: "top",
      advance: "continue",
      optional: true,
    },
  ],
  "runtime-policies": [
    {
      target: '[data-tour="runtime-policies-new"]',
      title: "Create a runtime policy",
      body: "Write a policy first, then assign it to a project or agent.",
      placement: "bottom",
      optional: true,
    },
    {
      target: '[data-tour="runtime-policy-form-name"]',
      title: "Name the policy",
      body: "Use a name that explains the sandbox boundary this policy describes.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="runtime-policy-form-kind"]',
      title: "Choose the policy kind",
      body: "The kind determines whether the YAML controls network, filesystem, process, or inference behavior.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="runtime-policy-form-description"]',
      title: "Describe the boundary",
      body: "Add a short description so administrators can understand the policy without opening its YAML.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="runtime-policy-form-yaml"]',
      title: "Review the YAML",
      body: "The YAML is the runtime policy payload. Keep it within the supported deny-by-default policy shape.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="runtime-policy-form-actions"]',
      title: "Save the policy",
      body: "Validate the name, kind, and YAML, then use Save to store the runtime policy.",
      placement: "top",
      advance: "continue",
    },
  ],
  denials: [
    {
      target: '[data-tour="denials-refresh"]',
      title: "Refresh the log",
      body: "Reload the latest denials to inspect their runtime, path, and reason.",
      placement: "bottom",
    },
    {
      target: '[data-tour="denials-table"]',
      title: "Read blocked requests",
      body: "The table shows when a request was blocked, which runtime and category produced it, the host or path involved, and the scrubbed reason.",
      placement: "top",
      advance: "continue",
    },
  ],
  users: [
    {
      target: '[data-tour="users-new"]',
      title: "Add a user",
      body: "Create an account, set its initial role, and manage access later with policies.",
      placement: "bottom",
      completion: "route-changes",
      optional: true,
    },
    {
      target: '[data-tour="user-form-username"]',
      title: "Set the username",
      body: "Choose the name the person will use to sign in to the dashboard.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="user-form-password"]',
      title: "Create a password",
      body: "Enter an initial password that meets the minimum length requirement, then repeat it in the confirmation field.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="user-form-role"]',
      title: "Choose the default role",
      body: "The role selects the default access bundle at creation; PBAC policies and groups can refine access afterward.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="user-form-actions"]',
      title: "Create the account",
      body: "Review the identity and role, then use Create user when the password fields are complete.",
      placement: "top",
      advance: "continue",
    },
  ],
  groups: [
    {
      target: '[data-tour="groups-new"]',
      title: "Create a group",
      body: "Add a group, then manage its members and policy bindings.",
      placement: "bottom",
      completion: "route-changes",
      optional: true,
    },
    {
      target: '[data-tour="group-form-name"]',
      title: "Name the group",
      body: "Choose a stable group name that describes the people who will share access.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="group-form-description"]',
      title: "Describe the group",
      body: "Add an optional description to make the group's purpose clear to other administrators.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="group-form-actions"]',
      title: "Save the group",
      body: "Use Create group once the name and description reflect the collection you want to manage.",
      placement: "top",
      advance: "continue",
    },
  ],
  policies: [
    {
      target: '[data-tour="policies-new"]',
      title: "Create a policy",
      body: "Add permission rules, then bind the policy to the principals who need them.",
      placement: "bottom",
      completion: "route-changes",
      optional: true,
    },
    {
      target: '[data-tour="policy-form-name"]',
      title: "Name the policy",
      body: "Use a name that explains the access bundle this policy grants.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="policy-form-description"]',
      title: "Describe the access",
      body: "Add an optional description to record the policy's purpose and intended principals.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="policy-form-actions"]',
      title: "Save the policy",
      body: "Use Create policy after reviewing the name and description. Rules and assignments can then be managed from the policy.",
      placement: "top",
      advance: "continue",
    },
  ],
  audit: [
    {
      target: '[data-tour="audit-refresh"]',
      title: "Refresh the audit trail",
      body: "Reload the latest entries and use the filters to narrow the history.",
      placement: "bottom",
    },
    {
      target: '[data-tour="audit-filters"]',
      title: "Filter the history",
      body: "Use the action and actor filters to narrow the configuration changes shown in the audit trail.",
      placement: "bottom",
      advance: "continue",
    },
    {
      target: '[data-tour="audit-table"]',
      title: "Inspect an entry",
      body: "Each row records the actor, action, target, and time. Entries with details can be expanded for the full audit payload.",
      placement: "top",
      advance: "continue",
    },
    {
      target: '[data-tour="audit-pagination"]',
      title: "Move through older entries",
      body: "Use the pagination controls to review newer or older audit pages when the history is longer than one view.",
      placement: "top",
      advance: "continue",
      optional: true,
    },
  ],
  system: [
    {
      target: '[data-tour="system-settings"]',
      title: "Runtime controls",
      body: "Set polling, retry, cycle, and timeout values from the editable settings.",
      placement: "bottom",
      advance: "continue",
    },
    {
      target: '[data-tour="system-settings-form"]',
      title: "Edit workflow values",
      body: "These fields control polling cadence, cycle limits, retries, timeouts, and ticket-close backoff. Values are applied at runtime.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="system-runtime"]',
      title: "Check runtime status",
      body: "The Runtime section shows the current polling state and environment values alongside the editable settings.",
      placement: "right",
      advance: "continue",
    },
    {
      target: '[data-tour="system-save"]',
      title: "Save settings",
      body: "When you have made the desired changes, use Save changes to hot-apply them. Read-only users can review the values without this action.",
      placement: "top",
      advance: "continue",
      optional: true,
    },
  ],
};

export type TutorialViewId = "overview" | "tasks" | "config";
export type TutorialKey = "main-nav" | "config-workflow" | `config-${Exclude<ConfigSectionId, "overview">}-v2`;

export interface TutorialSelection {
  key: TutorialKey;
  steps: TourStep[];
}

export function contextualTutorialKey(section: Exclude<ConfigSectionId, "overview">): TutorialKey {
  return `config-${section}-v2`;
}

export function selectTutorial(view: TutorialViewId, configSection: ConfigSectionId): TutorialSelection {
  if (view !== "config") return { key: "main-nav", steps: MAIN_NAV_TOUR };
  if (configSection === "overview") return { key: "config-workflow", steps: CONFIG_WORKFLOW_TOUR };
  const key = contextualTutorialKey(configSection);
  return { key, steps: CONFIG_SECTION_TOURS[configSection] };
}
