export type TaskState =
  | "DETECTED" | "CONTEXT_BUILDING" | "AGENT_RUNNING"
  | "IN_REVIEW" | "FEEDBACK_PROCESSING" | "RETRY_CYCLE"
  | "MERGED" | "CLOSING" | "DONE" | "FAILED" | "ABANDONED"
  | "REVIEW_PENDING" | "REVIEW_RUNNING" | "REVIEW_COMMENTING"
  | "REVIEW_WATCHING" | "REVIEW_DONE" | "REVIEW_FAILED";
