import { closeSync, constants, fstatSync, openSync, readFileSync, realpathSync } from "node:fs";
import { relative, resolve, sep } from "node:path";
import { isGeneratedSshFilePath } from "./sshKeyResolver.js";

const CONTAINER_SECRETS_ROOT = "/app/secrets";
function isInside(root: string, candidate: string): boolean {
  const rel = relative(root, candidate);
  return rel.length > 0 && rel !== ".." && !rel.startsWith(`..${sep}`);
}

function configuredSecretsRoots(): string[] {
  return Array.from(new Set([resolve(CONTAINER_SECRETS_ROOT), resolve(process.cwd(), "secrets")]));
}

function resolveOpenedFilePath(fd: number): string {
  let procError: unknown;
  try {
    return String(realpathSync(`/proc/self/fd/${fd}`));
  } catch (error) {
    procError = error;
  }
  try {
    return String(realpathSync(`/dev/fd/${fd}`));
  } catch (devError) {
    throw new Error("Unable to resolve the opened SSH file descriptor.", {
      cause: new AggregateError([procError, devError]),
    });
  }
}

/** Return whether a user-configured SSH file path is contained in an approved secrets root. */
export function isConfiguredSshFilePathAllowed(filePath: string): boolean {
  const candidate = resolve(filePath);
  return configuredSecretsRoots().some((root) => isInside(root, candidate));
}

/** Validate an SSH file immediately before reading it from the orchestrator host. */
export function assertSshFilePathAllowed(filePath: string, label: string): void {
  const candidate = resolve(filePath);
  const configuredRoot = configuredSecretsRoots().find((root) => isInside(root, candidate));

  if (configuredRoot !== undefined) {
    let resolvedCandidate: string;
    let resolvedRoot: string;
    try {
      resolvedCandidate = String(realpathSync(candidate));
      resolvedRoot = String(realpathSync(configuredRoot));
    } catch (err) {
      throw new Error(`${label} file not found or unreadable: ${filePath}`, { cause: err });
    }
    if (!isInside(resolvedRoot, resolvedCandidate)) {
      throw new Error(`${label} path resolves outside its approved secrets directory: ${filePath}`);
    }
    return;
  }

  if (isGeneratedSshFilePath(candidate)) return;

  throw new Error(`${label} path must be inside an approved secrets directory or generated by this process: ${filePath}`);
}

/** Validate and read an SSH file through one no-follow descriptor. */
export function readSshFileSecure(filePath: string, label: string): Buffer {
  const candidate = resolve(filePath);
  const configuredRoot = configuredSecretsRoots().find((root) => isInside(root, candidate));
  const generated = isGeneratedSshFilePath(candidate);
  if (configuredRoot === undefined && !generated) {
    throw new Error(`${label} path must be inside an approved secrets directory or generated by this process: ${filePath}`);
  }

  let fd: number;
  try {
    fd = openSync(candidate, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0));
  } catch (err) {
    throw new Error(`${label} file not found, unreadable, or a symbolic link: ${filePath}`, { cause: err });
  }

  try {
    const stat = fstatSync(fd);
    if (!stat.isFile()) throw new Error(`${label} path is not a regular file: ${filePath}`);
    if (generated) {
      const uid = process.getuid?.();
      if (uid !== undefined && stat.uid !== uid) {
        throw new Error(`${label} generated file is not owned by this process user: ${filePath}`);
      }
    } else if (configuredRoot !== undefined) {
      const openedPath = resolveOpenedFilePath(fd);
      const resolvedRoot = String(realpathSync(configuredRoot));
      if (!isInside(resolvedRoot, openedPath)) {
        throw new Error(`${label} path resolves outside its approved secrets directory: ${filePath}`);
      }
    }
    return readFileSync(fd);
  } finally {
    closeSync(fd);
  }
}
