import { mkdir, writeFile } from "fs/promises";
import { dirname, join } from "path";
import type {
  AgentAdapter,
  AgentResult,
  TaskContext,
  ExternalChangeId,
  AdapterContainerSpec,
} from "../interfaces.js";
import { makeExternalChangeId } from "../interfaces.js";

/**
 * MockAgentAdapter — deterministic adapter for validating the host-owned
 * workflow without calling a real LLM or spawning a container.
 */
export interface MockAgentOptions {
  status?: AgentResult["status"];
  /** Files to create/modify relative to the mounted repository root */
  filesToWrite?: Record<string, string>;
  summary?: string;
  simulateDelayMs?: number;
}

export class MockAgentAdapter implements AgentAdapter {
  readonly name = "mock";

  constructor(private readonly options: MockAgentOptions = {}) {}

  /** Return a minimal container spec (unused by MockAgentAdapter but required by the interface). */
  buildContainerSpec(_context: TaskContext): AdapterContainerSpec {
    return {
      image: "virtual-engineer-workspace:latest",
      env: {},
      command: ["node", "/agent-worker/dist/index.js"],
      additionalDockerArgs: [],
    };
  }

  /** Simulate an agent run by writing fixture files to the workspace and returning a result. */
  async execute(context: TaskContext): Promise<AgentResult> {
    if (this.options.simulateDelayMs) {
      await sleep(this.options.simulateDelayMs);
    }

    const status = this.options.status ?? "success";
    const changeId = context.agentSession.existingChangeId ?? this.generateChangeId();

    if (status !== "success") {
      return {
        status,
        modifiedFiles: [],
        summary: this.options.summary ?? `Mock agent returning ${status}`,
        agentLogs: `Mock agent: status=${status}`,
        externalChangeId: context.agentSession.existingChangeId,
        metadata: { adapter: "mock" },
      };
    }

    const repoPath = context.workspacePath;

    const filesToWrite = this.options.filesToWrite ?? {
      "MOCK_CHANGE.txt": [
        `Task: ${context.taskId}`,
        `Cycle: ${context.cycleNumber}`,
        `Ticket: ${context.ticketTitle}`,
        `Generated by MockAgentAdapter to validate the Gerrit flow.`,
      ].join("\n"),
    };

    const modifiedFiles: string[] = [];
    for (const [relativePath, content] of Object.entries(filesToWrite)) {
      const fullPath = join(repoPath, relativePath);
      await mkdir(dirname(fullPath), { recursive: true });
      await writeFile(fullPath, content, "utf8");
      modifiedFiles.push(relativePath);
    }

    const logs = [
      `Mock agent executed for task ${context.taskId}`,
      `Cycle: ${context.cycleNumber}`,
      `Feedback items received: ${context.priorFeedback.length}`,
      `Files written: ${modifiedFiles.join(", ")}`,
      "Commit SHA: host-managed",
      `Change-Id: ${changeId}`,
    ].join("\n");

    return {
      status: "success",
      modifiedFiles,
      summary: this.options.summary ?? `Applied changes for: ${context.ticketTitle}`,
      agentLogs: logs,
      externalChangeId: changeId,
      metadata: { adapter: "mock", cycleNumber: context.cycleNumber },
    };
  }

  /** Generate a deterministic mock Gerrit Change-Id. */
  private generateChangeId(): ExternalChangeId {
    return makeExternalChangeId("Imockchange1234");
  }
}

/** Resolve after the given number of milliseconds. */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
